"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.oEncypt = exports.oDecrypt = exports.decrypt = exports.encrypt = exports.BulkSave = exports.IBaseModule = exports.TableBuilder = void 0;
var expo_sql_wrapper_types_1 = require("./expo.sql.wrapper.types");
Object.defineProperty(exports, "IBaseModule", { enumerable: true, get: function () { return expo_sql_wrapper_types_1.IBaseModule; } });
var Database_1 = require("./Database");
var TableStructor_1 = require("./TableStructor");
exports.TableBuilder = TableStructor_1.default;
var BulkSave_1 = require("./BulkSave");
exports.BulkSave = BulkSave_1.default;
var UsefullMethods_1 = require("./UsefullMethods");
var encrypt = UsefullMethods_1.Functions.encrypt.bind(UsefullMethods_1.Functions);
exports.encrypt = encrypt;
var decrypt = UsefullMethods_1.Functions.decrypt.bind(UsefullMethods_1.Functions);
exports.decrypt = decrypt;
var oDecrypt = UsefullMethods_1.Functions.oDecrypt.bind(UsefullMethods_1.Functions);
exports.oDecrypt = oDecrypt;
var oEncypt = UsefullMethods_1.Functions.oEncypt.bind(UsefullMethods_1.Functions);
exports.oEncypt = oEncypt;
exports.default = Database_1.default;
