export const StylesAttributes = [
  "alignContent",
  "alignItems",
  "alignSelf",
  "aspectRatio",
  "backfaceVisibility",
  "backgroundColor",
  "borderBottomColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomWidth",
  "borderColor",
  "borderLeftColor",
  "borderLeftWidth",
  "borderRadius",
  "borderRightColor",
  "borderRightWidth",
  "borderStyle",
  "borderTopColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "color",
  "decomposedMatrix",
  "direction",
  "display",
  "elevation",
  "flex",
  "flexBasis",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexWrap",
  "fontFamily",
  "fontSize",
  "fontStyle",
  "fontVariant",
  "fontWeight",
  "height",
  "includeFontPadding",
  "justifyContent",
  "left",
  "letterSpacing",
  "lineHeight",
  "margin",
  "marginBottom",
  "marginHorizontal",
  "marginLeft",
  "marginRight",
  "marginTop",
  "marginVertical",
  "maxHeight",
  "maxWidth",
  "minHeight",
  "minWidth",
  "opacity",
  "overflow",
  "overlayColor",
  "padding",
  "paddingBottom",
  "paddingHorizontal",
  "paddingLeft",
  "paddingRight",
  "paddingTop",
  "paddingVertical",
  "position",
  "resizeMode",
  "right",
  "rotation",
  "scaleX",
  "scaleY",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "textAlign",
  "textAlignVertical",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "textShadowColor",
  "textShadowOffset",
  "textShadowRadius",
  "tintColor",
  "top",
  "transform",
  "transformMatrix",
  "translateX",
  "translateY",
  "width",
  "writingDirection",
  "zIndex"
]

export const ShortCSS =
{
  textTransform: 'textTransform',
  alignContent: 'alignContent',
  alC: 'alignContent',
  alignItems: 'alignItems',
  alI: 'alignItems',
  alignSelf: 'alignSelf',
  alS: 'alignSelf',
  aspectRatio: 'aspectRatio',
  asR: 'aspectRatio',
  backfaceVisibility: 'backfaceVisibility',
  baV: 'backfaceVisibility',
  backgroundColor: 'backgroundColor',
  baC: 'backgroundColor',
  borderBottomColor: 'borderBottomColor',
  boBC: 'borderBottomColor',
  borderBottomLeftRadius: 'borderBottomLeftRadius',
  boBLR: 'borderBottomLeftRadius',
  borderBottomRightRadius: 'borderBottomRightRadius',
  boBRR: 'borderBottomRightRadius',
  borderBottomWidth: 'borderBottomWidth',
  boBW: 'borderBottomWidth',
  borderColor: 'borderColor',
  boC: 'borderColor',
  borderLeftColor: 'borderLeftColor',
  boLC: 'borderLeftColor',
  borderLeftWidth: 'borderLeftWidth',
  boLW: 'borderLeftWidth',
  borderRadius: 'borderRadius',
  boR: 'borderRadius',
  borderRightColor: 'borderRightColor',
  boRC: 'borderRightColor',
  borderRightWidth: 'borderRightWidth',
  boRW: 'borderRightWidth',
  borderStyle: 'borderStyle',
  boS: 'borderStyle',
  borderTopColor: 'borderTopColor',
  boTC: 'borderTopColor',
  borderTopLeftRadius: 'borderTopLeftRadius',
  boTLR: 'borderTopLeftRadius',
  borderTopRightRadius: 'borderTopRightRadius',
  boTRR: 'borderTopRightRadius',
  borderTopWidth: 'borderTopWidth',
  boTW: 'borderTopWidth',
  borderWidth: 'borderWidth',
  boW: 'borderWidth',
  bottom: 'bottom',
  bo: 'bottom',
  color: 'color',
  co: 'color',
  decomposedMatrix: 'decomposedMatrix',
  deM: 'decomposedMatrix',
  direction: 'direction',
  dir: 'direction',
  display: 'display',
  di: 'display',
  elevation: 'elevation',
  el: 'elevation',
  flex: 'flex',
  fl: 'flex',
  flexBasis: 'flexBasis',
  flB: 'flexBasis',
  flexDirection: 'flexDirection',
  flD: 'flexDirection',
  flexGrow: 'flexGrow',
  flG: 'flexGrow',
  flexShrink: 'flexShrink',
  flS: 'flexShrink',
  flexWrap: 'flexWrap',
  flW: 'flexWrap',
  fontFamily: 'fontFamily',
  foF: 'fontFamily',
  fontSize: 'fontSize',
  foS: 'fontStyle',
  fontStyle: 'fontStyle',
  fontVariant: 'fontVariant',
  foV: 'fontVariant',
  fontWeight: 'fontWeight',
  foW: 'fontWeight',
  height: 'height',
  he: 'height',
  includeFontPadding: 'includeFontPadding',
  inFP: 'includeFontPadding',
  justifyContent: 'justifyContent',
  juC: 'justifyContent',
  left: 'left',
  le: 'left',
  letterSpacing: 'letterSpacing',
  leS: 'letterSpacing',
  lineHeight: 'lineHeight',
  liH: 'lineHeight',
  margin: 'margin',
  ma: 'margin',
  marginBottom: 'marginBottom',
  maB: 'marginBottom',
  marginHorizontal: 'marginHorizontal',
  maHo: 'marginHorizontal',
  marginLeft: 'marginLeft',
  maL: 'marginLeft',
  marginRight: 'marginRight',
  maR: 'marginRight',
  marginTop: 'marginTop',
  maT: 'marginTop',
  marginVertical: 'marginVertical',
  maV: 'marginVertical',
  maxHeight: 'maxHeight',
  maH: 'maxHeight',
  maxWidth: 'maxWidth',
  maW: 'maxWidth',
  minHeight: 'minHeight',
  miH: 'minHeight',
  minWidth: 'minWidth',
  miW: 'minWidth',
  opacity: 'opacity',
  op: 'opacity',
  overflow: 'overflow',
  ov: 'overflow',
  overlayColor: 'overlayColor',
  ovC: 'overlayColor',
  padding: 'padding',
  pa: 'padding',
  paddingBottom: 'paddingBottom',
  paB: 'paddingBottom',
  paddingHorizontal: 'paddingHorizontal',
  paH: 'paddingHorizontal',
  paddingLeft: 'paddingLeft',
  paL: 'paddingLeft',
  paddingRight: 'paddingRight',
  paR: 'paddingRight',
  paddingTop: 'paddingTop',
  paT: 'paddingTop',
  paddingVertical: 'paddingVertical',
  paV: 'paddingVertical',
  position: 'position',
  po: 'position',
  resizeMode: 'resizeMode',
  reM: 'resizeMode',
  right: 'right',
  ri: 'right',
  rotation: 'rotation',
  ro: 'rotation',
  scaleX: 'scaleX',
  scX: 'scaleX',
  scaleY: 'scaleY',
  scY: 'scaleY',
  shadowColor: 'shadowColor',
  shC: 'shadowColor',
  shadowOffset: 'shadowOffset',
  shO: 'shadowOpacity',
  shadowOpacity: 'shadowOpacity',
  shadowRadius: 'shadowRadius',
  shR: 'shadowRadius',
  textAlign: 'textAlign',
  teA: 'textAlign',
  textAlignVertical: 'textAlignVertical',
  teAV: 'textAlignVertical',
  textDecorationColor: 'textDecorationColor',
  teDC: 'textDecorationColor',
  textDecorationLine: 'textDecorationLine',
  teDL: 'textDecorationLine',
  textDecorationStyle: 'textDecorationStyle',
  teDS: 'textDecorationStyle',
  textShadowColor: 'textShadowColor',
  teSC: 'textShadowColor',
  textShadowOffset: 'textShadowOffset',
  teSO: 'textShadowOffset',
  textShadowRadius: 'textShadowRadius',
  teSR: 'textShadowRadius',
  tintColor: 'tintColor',
  tiC: 'tintColor',
  top: 'top',
  to: 'top',
  transform: 'transform',
  tr: 'transform',
  transformMatrix: 'transformMatrix',
  trM: 'transformMatrix',
  translateX: 'translateX',
  trX: 'translateX',
  translateY: 'translateY',
  trY: 'translateY',
  width: 'width',
  wi: 'width',
  writingDirection: 'writingDirection',
  wrD: 'writingDirection',
  zIndex: 'zIndex',
  zI: 'zIndex',
  texttransform: 'textTransform',
  aligncontent: 'alignContent',
  alc: 'alignContent',
  alignitems: 'alignItems',
  ali: 'alignItems',
  alignself: 'alignSelf',
  als: 'alignSelf',
  aspectratio: 'aspectRatio',
  asr: 'aspectRatio',
  backfacevisibility: 'backfaceVisibility',
  bav: 'backfaceVisibility',
  backgroundcolor: 'backgroundColor',
  bac: 'backgroundColor',
  borderbottomcolor: 'borderBottomColor',
  bobc: 'borderBottomColor',
  borderbottomleftradius: 'borderBottomLeftRadius',
  boblr: 'borderBottomLeftRadius',
  borderbottomrightradius: 'borderBottomRightRadius',
  bobrr: 'borderBottomRightRadius',
  borderbottomwidth: 'borderBottomWidth',
  bobw: 'borderBottomWidth',
  bordercolor: 'borderColor',
  boc: 'borderColor',
  borderleftcolor: 'borderLeftColor',
  bolc: 'borderLeftColor',
  borderleftwidth: 'borderLeftWidth',
  bolw: 'borderLeftWidth',
  borderradius: 'borderRadius',
  bor: 'borderRadius',
  borderrightcolor: 'borderRightColor',
  borc: 'borderRightColor',
  borderrightwidth: 'borderRightWidth',
  borw: 'borderRightWidth',
  borderstyle: 'borderStyle',
  bos: 'borderStyle',
  bordertopcolor: 'borderTopColor',
  botc: 'borderTopColor',
  bordertopleftradius: 'borderTopLeftRadius',
  botlr: 'borderTopLeftRadius',
  bordertoprightradius: 'borderTopRightRadius',
  botrr: 'borderTopRightRadius',
  bordertopwidth: 'borderTopWidth',
  botw: 'borderTopWidth',
  borderwidth: 'borderWidth',
  bow: 'borderWidth',
  decomposedmatrix: 'decomposedMatrix',
  dem: 'decomposedMatrix',
  flexbasis: 'flexBasis',
  flb: 'flexBasis',
  flexdirection: 'flexDirection',
  fld: 'flexDirection',
  flexgrow: 'flexGrow',
  flg: 'flexGrow',
  flexshrink: 'flexShrink',
  fls: 'flexShrink',
  flexwrap: 'flexWrap',
  flw: 'flexWrap',
  fontfamily: 'fontFamily',
  fof: 'fontFamily',
  fontsize: 'fontSize',
  fos: 'fontSize',
  fontstyle: 'fontStyle',
  fontvariant: 'fontVariant',
  fov: 'fontVariant',
  fontweight: 'fontWeight',
  fow: 'fontWeight',
  includefontpadding: 'includeFontPadding',
  infp: 'includeFontPadding',
  justifycontent: 'justifyContent',
  juc: 'justifyContent',
  letterspacing: 'letterSpacing',
  les: 'letterSpacing',
  lineheight: 'lineHeight',
  lih: 'lineHeight',
  marginbottom: 'marginBottom',
  mab: 'marginBottom',
  marginhorizontal: 'marginHorizontal',
  maho: 'marginHorizontal',
  marginleft: 'marginLeft',
  mal: 'marginLeft',
  marginright: 'marginRight',
  mar: 'marginRight',
  margintop: 'marginTop',
  mat: 'marginTop',
  marginvertical: 'marginVertical',
  mav: 'marginVertical',
  maxheight: 'maxHeight',
  mah: 'maxHeight',
  maxwidth: 'maxWidth',
  maw: 'maxWidth',
  minheight: 'minHeight',
  mih: 'minHeight',
  minwidth: 'minWidth',
  miw: 'minWidth',
  overlaycolor: 'overlayColor',
  ovc: 'overlayColor',
  paddingbottom: 'paddingBottom',
  pab: 'paddingBottom',
  paddinghorizontal: 'paddingHorizontal',
  pah: 'paddingHorizontal',
  paddingleft: 'paddingLeft',
  pal: 'paddingLeft',
  paddingright: 'paddingRight',
  par: 'paddingRight',
  paddingtop: 'paddingTop',
  pat: 'paddingTop',
  paddingvertical: 'paddingVertical',
  pav: 'paddingVertical',
  resizemode: 'resizeMode',
  rem: 'resizeMode',
  scalex: 'scaleX',
  scx: 'scaleX',
  scaley: 'scaleY',
  scy: 'scaleY',
  shadowcolor: 'shadowColor',
  shc: 'shadowColor',
  shadowoffset: 'shadowOffset',
  sho: 'shadowOpacity',
  shadowopacity: 'shadowOpacity',
  shadowradius: 'shadowRadius',
  shr: 'shadowRadius',
  textalign: 'textAlign',
  tea: 'textAlign',
  textalignvertical: 'textAlignVertical',
  teav: 'textAlignVertical',
  textdecorationcolor: 'textDecorationColor',
  tedc: 'textDecorationColor',
  textdecorationline: 'textDecorationLine',
  tedl: 'textDecorationLine',
  textdecorationstyle: 'textDecorationStyle',
  teds: 'textDecorationStyle',
  textshadowcolor: 'textShadowColor',
  tesc: 'textShadowColor',
  textshadowoffset: 'textShadowOffset',
  teso: 'textShadowOffset',
  textshadowradius: 'textShadowRadius',
  tesr: 'textShadowRadius',
  tintcolor: 'tintColor',
  tic: 'tintColor',
  transformmatrix: 'transformMatrix',
  trm: 'transformMatrix',
  translatex: 'translateX',
  trx: 'translateX',
  translatey: 'translateY',
  try: 'translateY',
  writingdirection: 'writingDirection',
  wrd: 'writingDirection',
  zindex: 'zIndex',
  zi: 'zIndex',
  outlineStyle: "outlineStyle",
  ouS: "outlineStyle"
}



export const ShortStyles = {
  outlineStyle: "outlineStyle",
  ouS: "outlineStyle",
  "textTransform": "textTransform",
  "alignContent": " alignContent:",
  "alC": " alignContent:",
  "alignItems": " alignItems:",
  "alI": " alignItems:",
  "alignSelf": " alignSelf:",
  "alS": " alignSelf:",
  "aspectRatio": " aspectRatio:",
  "asR": " aspectRatio:",
  "backfaceVisibility": " backfaceVisibility:",
  "baV": " backfaceVisibility:",
  "backgroundColor": " backgroundColor:",
  "baC": " backgroundColor:",
  "borderBottomColor": " borderBottomColor:",
  "boBC": " borderBottomColor:",
  "borderBottomLeftRadius": " borderBottomLeftRadius:",
  "boBLR": " borderBottomLeftRadius:",
  "borderBottomRightRadius": " borderBottomRightRadius:",
  "boBRR": " borderBottomRightRadius:",
  "borderBottomWidth": " borderBottomWidth:",
  "boBW": " borderBottomWidth:",
  "borderColor": " borderColor:",
  "boC": " borderColor:",
  "borderLeftColor": " borderLeftColor:",
  "boLC": " borderLeftColor:",
  "borderLeftWidth": " borderLeftWidth:",
  "boLW": " borderLeftWidth:",
  "borderRadius": " borderRadius:",
  "boR": " borderRadius:",
  "borderRightColor": " borderRightColor:",
  "boRC": " borderRightColor:",
  "borderRightWidth": " borderRightWidth:",
  "boRW": " borderRightWidth:",
  "borderStyle": " borderStyle:",
  "boS": " borderStyle:",
  "borderTopColor": " borderTopColor:",
  "boTC": " borderTopColor:",
  "borderTopLeftRadius": " borderTopLeftRadius:",
  "boTLR": " borderTopLeftRadius:",
  "borderTopRightRadius": " borderTopRightRadius:",
  "boTRR": " borderTopRightRadius:",
  "borderTopWidth": " borderTopWidth:",
  "boTW": " borderTopWidth:",
  "borderWidth": " borderWidth:",
  "boW": " borderWidth:",
  "bottom": " bottom:",
  "bo": " bottom:",
  "color": " color:",
  "co": " color:",
  "decomposedMatrix": " decomposedMatrix:",
  "deM": " decomposedMatrix:",
  "direction": " direction:",
  "dir": " direction:",
  "display": " display:",
  "di": " display:",
  "elevation": " elevation:",
  "el": " elevation:",
  "flex": " flex:",
  "fl": " flex:",
  "flexBasis": " flexBasis:",
  "flB": " flexBasis:",
  "flexDirection": " flexDirection:",
  "flD": " flexDirection:",
  "flexGrow": " flexGrow:",
  "flG": " flexGrow:",
  "flexShrink": " flexShrink:",
  "flS": " flexShrink:",
  "flexWrap": " flexWrap:",
  "flW": " flexWrap:",
  "fontFamily": " fontFamily:",
  "foF": " fontFamily:",
  "fontSize": " fontSize:",
  "foS": " fontSize:",
  "fontStyle": " fontStyle:",
  "fontVariant": " fontVariant:",
  "foV": " fontVariant:",
  "fontWeight": " fontWeight:",
  "foW": " fontWeight:",
  "height": " height:",
  "he": " height:",
  "includeFontPadding": " includeFontPadding:",
  "inFP": " includeFontPadding:",
  "justifyContent": " justifyContent:",
  "juC": " justifyContent:",
  "left": " left:",
  "le": " left:",
  "letterSpacing": " letterSpacing:",
  "leS": " letterSpacing:",
  "lineHeight": " lineHeight:",
  "liH": " lineHeight:",
  "margin": " margin:",
  "ma": " margin:",
  "marginBottom": " marginBottom:",
  "maB": " marginBottom:",
  "marginHorizontal": " marginHorizontal:",
  "maHo": " marginHorizontal:",
  "marginLeft": " marginLeft:",
  "maL": " marginLeft:",
  "marginRight": " marginRight:",
  "maR": " marginRight:",
  "marginTop": " marginTop:",
  "maT": " marginTop:",
  "marginVertical": " marginVertical:",
  "maV": " marginVertical:",
  "maxHeight": " maxHeight:",
  "maH": " maxHeight:",
  "maxWidth": " maxWidth:",
  "maW": " maxWidth:",
  "minHeight": " minHeight:",
  "miH": " minHeight:",
  "minWidth": " minWidth:",
  "miW": " minWidth:",
  "opacity": " opacity:",
  "op": " opacity:",
  "overflow": " overflow:",
  "ov": " overflow:",
  "overlayColor": " overlayColor:",
  "ovC": " overlayColor:",
  "padding": " padding:",
  "pa": " padding:",
  "paddingBottom": " paddingBottom:",
  "paB": " paddingBottom:",
  "paddingHorizontal": " paddingHorizontal:",
  "paH": " paddingHorizontal:",
  "paddingLeft": " paddingLeft:",
  "paL": " paddingLeft:",
  "paddingRight": " paddingRight:",
  "paR": " paddingRight:",
  "paddingTop": " paddingTop:",
  "paT": " paddingTop:",
  "paddingVertical": " paddingVertical:",
  "paV": " paddingVertical:",
  "position": " position:",
  "po": " position:",
  "resizeMode": " resizeMode:",
  "reM": " resizeMode:",
  "right": " right:",
  "ri": " right:",
  "rotation": " rotation:",
  "ro": " rotation:",
  "scaleX": " scaleX:",
  "scX": " scaleX:",
  "scaleY": " scaleY:",
  "scY": " scaleY:",
  "shadowColor": " shadowColor:",
  "shC": " shadowColor:",
  "shadowOffset": " shadowOffset:",
  "shO": " shadowOpacity:",
  "shadowOpacity": " shadowOpacity:",
  "shadowRadius": " shadowRadius:",
  "shR": " shadowRadius:",
  "textAlign": " textAlign:",
  "teA": " textAlign:",
  "textAlignVertical": " textAlignVertical:",
  "teAV": " textAlignVertical:",
  "textDecorationColor": " textDecorationColor:",
  "teDC": " textDecorationColor:",
  "textDecorationLine": " textDecorationLine:",
  "teDL": " textDecorationLine:",
  "textDecorationStyle": " textDecorationStyle:",
  "teDS": " textDecorationStyle:",
  "textShadowColor": " textShadowColor:",
  "teSC": " textShadowColor:",
  "textShadowOffset": " textShadowOffset:",
  "teSO": " textShadowOffset:",
  "textShadowRadius": " textShadowRadius:",
  "teSR": " textShadowRadius:",
  "tintColor": " tintColor:",
  "tiC": " tintColor:",
  "top": " top:",
  "to": " top:",
  "transform": " transform:",
  "tr": " transform:",
  "transformMatrix": " transformMatrix:",
  "trM": " transformMatrix:",
  "translateX": " translateX:",
  "trX": " translateX:",
  "translateY": " translateY:",
  "trY": " translateY:",
  "width": " width:",
  "wi": " width:",
  "writingDirection": " writingDirection:",
  "wrD": " writingDirection:",
  "zIndex": " zIndex:",
  "zI": " zIndex:"
}


